# This is a basic workflow to help you get started with Actions

name: Deploy Shoestore to surge

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: NodeJS Setup
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12
        
    - name: Yarn Setup
      run: npm install -g yarn surge
      
    - name: Yarn Install Dependencies
      run: yarn install

    - name: Yarn Build
      run: yarn build
    
    - name: Surge Deployment
      run: surge ./build eru-shoestore.surge.sh --token ${{ secrets.SURGE_TOKEN }} 
